"""Writes guest/ovr_messages.h: the Oculus Platform SDK's message types.

Every Platform SDK request answers with a message whose type names the
request (Entitlement_GetIsViewerEntitled = 0x186B58B1, ...). The stand-in
platform in guest/platform.cpp has to use the same numbers, or the game's
callbacks never fire. The C# SDK inside every Unity game that uses the
platform carries them as the enum Oculus.Platform.Message.MessageType, so
they are read from the game's global-metadata.dat (version 31).

    python tools/gen_ovr_messages.py METADATA > guest/ovr_messages.h
"""

import struct
import sys


def compressed_uint(data, at):
    b = data[at]
    if b < 0x80:
        return b
    if (b & 0xC0) == 0x80:
        return ((b & 0x3F) << 8) | data[at + 1]
    if (b & 0xE0) == 0xC0:
        return ((b & 0x1F) << 24) | (data[at + 1] << 16) | (data[at + 2] << 8) | data[at + 3]
    if b == 0xF0:
        return struct.unpack_from("<I", data, at + 1)[0]
    if b == 0xFE:
        return 0xFFFFFFFE
    if b == 0xFF:
        return 0xFFFFFFFF
    raise ValueError(f"bad compressed integer lead byte {b:#x}")


def main():
    m = open(sys.argv[1], "rb").read()
    sections = struct.unpack_from("<62I", m, 8)
    section = lambda n: (sections[2 * n], sections[2 * n + 1])
    string_off, _ = section(2)

    def string(index):
        return m[string_off + index:m.index(b"\0", string_off + index)].decode("utf-8", "replace")

    defaults_off, defaults_size = section(7)  # fieldDefaultValues: field, type, data index
    data_off, _ = section(8)
    defaults = {}
    for i in range(defaults_size // 12):
        field, _type, data = struct.unpack_from("<3i", m, defaults_off + i * 12)
        defaults[field] = data

    fields_off, _ = section(11)  # fields: name, type, token (12 bytes)
    types_off, types_size = section(19)
    best = None
    for t in range(types_size // 88):
        base = types_off + t * 88
        name = struct.unpack_from("<i", m, base)[0]
        if string(name) != "MessageType":
            continue
        field_start = struct.unpack_from("<i", m, base + 8 * 4)[0]
        field_count = struct.unpack_from("<H", m, base + 64 + 4)[0]
        if best is None or field_count > best[1]:
            best = (field_start, field_count)
    if best is None:
        raise SystemExit("no MessageType enum in this metadata")

    entries = []
    for f in range(best[0], best[0] + best[1]):
        name = string(struct.unpack_from("<i", m, fields_off + f * 12)[0])
        if f not in defaults or name == "value__":
            continue
        entries.append((name, compressed_uint(m, data_off + defaults[f])))

    print("/* Generated by tools/gen_ovr_messages.py from the game's IL2CPP metadata:")
    print("   Oculus.Platform.Message.MessageType. Do not edit. */")
    print("#pragma once")
    print("#include <cstdint>")
    print()
    print("struct OvrMessageType {")
    print("    const char* name; /* the request function is ovr_<name> */")
    print("    uint32_t type;")
    print("};")
    print()
    print("static const OvrMessageType kOvrMessageTypes[] = {")
    for name, value in entries:
        print(f'    {{"{name}", 0x{value:08X}u}},')
    print("};")
    print(f"/* {len(entries)} message types */", file=sys.stderr)


if __name__ == "__main__":
    main()
