"""Generates guest/vk_table.h from the NDK's Vulkan headers.

For every Vulkan entry point the pass-through needs three facts it cannot
work out at run time: how many parameters there are (so arguments past the
eighth can be read from the guest stack), which of them are floats (AArch64
passes those in vector registers, Windows x64 in XMM registers by position),
and where the allocation callbacks go (they are guest function pointers the
host driver cannot call, so they are always replaced with null).

    python tools/gen_vk_table.py <ndk sysroot include/vulkan> guest/vk_table.h
"""
import re
import sys

src_dir, out_path = sys.argv[1], sys.argv[2]
text = ''
for name in ('vulkan_core.h', 'vulkan_android.h'):
    text += open(src_dir + '/' + name, encoding='utf-8').read()

proto = re.compile(r'VKAPI_ATTR\s+([\w\s\*]+?)\s+VKAPI_CALL\s+(vk\w+)\s*\((.*?)\);', re.S)
entries = {}
for returns, name, params in proto.findall(text):
    params = ' '.join(params.split())
    parts = [p.strip() for p in params.split(',')] if params and params != 'void' else []
    floats = 0
    allocator = -1
    for i, p in enumerate(parts):
        # A plain float, not a pointer to one.
        # An array parameter decays to a pointer, so it is not one.
        if '[' not in p and re.match(r'^(const\s+)?float\s+\w+$', p):
            floats |= 1 << i
        if 'VkAllocationCallbacks' in p:
            allocator = i
    kind = 0 if returns.strip() == 'void' else 1
    entries[name] = (len(parts), floats, allocator, kind)

with open(out_path, 'w', encoding='utf-8', newline='\n') as out:
    out.write('/* Generated by tools/gen_vk_table.py from the NDK Vulkan headers. Do not edit. */\n')
    out.write('#pragma once\n\n#include <cstdint>\n\n')
    out.write('struct VkSignature {\n    const char* name;\n    uint8_t params;\n    uint16_t floats;\n'
              '    int8_t allocator;\n    uint8_t returns;\n};\n\n')
    out.write('static const VkSignature kVkSignatures[] = {\n')
    for name in sorted(entries):
        n, f, a, k = entries[name]
        out.write('    {"%s", %d, 0x%x, %d, %d},\n' % (name, n, f, a, k))
    out.write('};\n')
print(len(entries), 'entry points;', sum(1 for e in entries.values() if e[1]), 'take floats')
