"""Generates guest/xr_table.h from the OpenXR headers, as gen_vk_table.py does
for Vulkan: for every entry point, how many parameters it takes and which of
them are floats, so the pass-through can read the guest's arguments and call
the host's function with them in the right registers.

    python tools/gen_xr_table.py third_party/openxr/include/openxr guest/xr_table.h
"""
import re
import sys

src_dir, out_path = sys.argv[1], sys.argv[2]
text = ''
for name in ('openxr.h', 'openxr_platform.h'):
    text += open(src_dir + '/' + name, encoding='utf-8').read()

proto = re.compile(r'XRAPI_ATTR\s+([\w\s\*]+?)\s+XRAPI_CALL\s+(xr\w+)\s*\((.*?)\);', re.S)
entries = {}
for returns, name, params in proto.findall(text):
    params = ' '.join(params.split())
    parts = [p.strip() for p in params.split(',')] if params and params != 'void' else []
    floats = 0
    for i, p in enumerate(parts):
        if '[' not in p and re.match(r'^(const\s+)?float\s+\w+$', p):
            floats |= 1 << i
    entries[name] = (len(parts), floats)

with open(out_path, 'w', encoding='utf-8', newline='\n') as out:
    out.write('/* Generated by tools/gen_xr_table.py from the OpenXR headers. Do not edit. */\n')
    out.write('#pragma once\n\n#include <cstdint>\n\n')
    out.write('struct XrSignature {\n    const char* name;\n    uint8_t params;\n    uint16_t floats;\n};\n\n')
    out.write('static const XrSignature kXrSignatures[] = {\n')
    for name in sorted(entries):
        n, f = entries[name]
        out.write('    {"%s", %d, 0x%x},\n' % (name, n, f))
    out.write('};\n')
print(len(entries), 'entry points;', [n for n, (c, f) in entries.items() if f])
