"""Writes guest/libc_names.h: every function and variable Android's libc, libm
and libdl export (API 34), from the NDK's stub libraries.

The linker binds these names to the runtime's own libc even when a game library
also exports one: on Android a library's imports search libc (in its own
dependency group) before anything loaded later, so an interposer such as
Crashpad's pthread_create wrapper only sees callers that asked for it, and its
dlsym(RTLD_NEXT, ...) finds the real one.

    python tools/gen_libc_names.py
"""
import os
import subprocess

NDK = r'C:/Users/joshu/android-sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/windows-x86_64'
LIBS = ['libc.so', 'libm.so', 'libdl.so']
names = set()
for lib in LIBS:
    path = f'{NDK}/sysroot/usr/lib/aarch64-linux-android/34/{lib}'
    out = subprocess.run([f'{NDK}/bin/llvm-readelf.exe', '--dyn-syms', path], capture_output=True, text=True,
                         check=True).stdout
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 8 and parts[6] != 'UND' and parts[3] in ('FUNC', 'OBJECT', 'IFUNC'):
            names.add(parts[7].split('@')[0])
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, '..', 'guest', 'libc_names.h'), 'w', newline='\n') as f:
    f.write('/* Generated by tools/gen_libc_names.py from the NDK (API 34). */\n#pragma once\n')
    f.write('static const char* const kLibcNames[] = {\n')
    for name in sorted(names):
        f.write(f'    "{name}",\n')
    f.write('};\n')
print(len(names), 'names')
